#!/bin/sh
#
# Ganymede build script
#
# Release: $Name:  $
# Version: $Revision: 1.4 $
# Date: $Date: 1999/04/06 20:54:45 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. ./config.sh

# And do the build

echo "Compiling $COMPNAME"

CLASSPATH=$CLASSDIR:$CLASSPATH; export CLASSPATH
$JAVAC -J-mx128m -deprecation -d $CLASSDIR *.java

# Return to our last directory

cd $currentdir

echo "Done compiling $COMPNAME"
