#!/bin/sh
#
# Ganymede build script
#
# Version: $Revision: 1.1 $
# Date: $Date: 1999/01/15 00:15:28 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

# And do the build

echo "Compiling $COMPNAME"

umask 0133;

CLASSPATH=$CLASSDIR:$CLASSPATH; export CLASSPATH
$JAVAC -J-mx128m -deprecation -d $CLASSDIR *.java

# Return to our last directory

cd $currentdir

echo "Done compiling $COMPNAME"
