#!/bin/sh
#
# Ganymede Server RMI build script
#
# Release: $Name:  $
# Version: $Revision: 1.6 $
# Date: $Date: 1999/04/28 08:20:00 $
#
############################################################

echo "Compiling RMI classes for Ganymede Server"

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

CLASSPATH=$CLASSDIR:$CLASSPATH; export CLASSPATH
RMICOMPILER=$JAVADIR/rmic; export RMICOMPILER

echo "Building rmi stubs and skeletons"

$RMICOMPILER -d $TARGETDIR arlut.csd.ganymede.DBField arlut.csd.ganymede.DBNameSpace arlut.csd.ganymede.DBObject arlut.csd.ganymede.DBObjectBase arlut.csd.ganymede.DBObjectBaseField arlut.csd.ganymede.DBSchemaEdit arlut.csd.ganymede.iAdmin arlut.csd.ganymede.GanymedeAdmin arlut.csd.ganymede.GanymedeServer arlut.csd.ganymede.GanymedeSession 

$RMICOMPILER -d $TARGETDIR arlut.csd.ganymede.PermissionMatrixDBField arlut.csd.ganymede.InvidDBField arlut.csd.ganymede.StringDBField arlut.csd.ganymede.BooleanDBField arlut.csd.ganymede.DateDBField arlut.csd.ganymede.NumericDBField arlut.csd.ganymede.PasswordDBField arlut.csd.ganymede.IPDBField arlut.csd.ganymede.GanymediatorWizard

$RMICOMPILER -d $TARGETDIR arlut.csd.ganymede.DBBaseCategory arlut.csd.ganymede.stopServerAdmin

echo "Done"
