#
# jcrypt Class config.sh
#
# Auto-generated by /home/broccol/ganymede/work/ganymede/configure
#

# Name of component package being built

COMPNAME="Java UUID Generator"

# Location of java compiler

JAVAC=/usr/java1.2/bin/javac

# Location of directory containing java executables

JAVADIR=/usr/java1.2/bin

# Master location for ganymede classes.. the java compiler
# will look here to find pre-compiled classes needed to compile
# code in this directory

CLASSDIR=/home/broccol/ganymede/classes:/opt/depot/swing-1.1.1/swingall.jar

# Target location for classes built from sources in this directory.
# This is just the root of the tree.. the javac compiler will
# place classes in a subdirectory of this directory according to
# the package name

TARGETDIR=/home/broccol/ganymede/classes

