#!/bin/sh
#
# Ganymede build script
#
# Version: $Revision: 1.7 $
# Date: $Date: 2004/03/24 03:42:09 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. ./config.sh

echo "Building custom jar file from compiled classes"

# And do the build

cd classes

mv -f $currentdir/../custom.jar $currentdir/../custom.jar.old > /dev/null 2>&1

$JAVADIR/jar -cf $currentdir/../custom.jar arlut net

cd $currentdir

echo "Done"

##################################################
