#!/bin/sh
#
# Ganymede GASH Customization Jar Script
#
###################################################

. config.sh

##################################################

echo "Building custom jar file from compiled classes"

cd $CLASSDIR

umask 0113;

mv -f $TARGETJAR $TARGETJAR.old > /dev/null 2>&1

jar -cf $TARGETJAR arlut

echo "Done"
