#!/bin/sh
#
# Ganymede build script
#
# Version: $Revision: 1.2 $
# Date: $Date: 1999/01/15 21:44:49 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

echo "Building custom jar file from compiled classes"

# And do the build

cd classes

mv -f $TARGETJAR $TARGETJAR.old > /dev/null 2>&1

$JAVADIR/jar -cf $TARGETJAR arlut

cd $currentdir

echo "Done"

##################################################