#!/bin/sh
base_directory=`dirname $0`
src_directory="../../`dirname $base_directory`"
timestamp=`date +"%Y%m%d-%H%M%S"`
if [ -z $1 ]
then
  echo "You need to give the location of your Ganymede server installation."
  exit 1
fi
rm -f server_output.log
ln -s server_output.log.$timestamp server_output.log
ant -f "$base_directory/run.xml" -DBASE_DIRECTORY="$src_directory" -DSERVER_DIRECTORY="$1" -DCWD_DIR="`pwd`" -DTIMESTAMP="$timestamp" runServer
