#!/bin/sh
#
# Ganymede build script for XML class tree
#
# Release: $Name:  $
# Version: $Revision: 1.3 $
# Date: $Date: 2000/02/21 22:34:10 $
#
############################################################

echo
echo "Compiling XML Classes"

# Build the OMG SAX Classes

cd sax
./build

# Build James Clark's XML Parser

cd ../xp
./build

echo "Done Compiling XML Classes"
echo
