#!/bin/sh
#
# Ganymede schema kit build script
#
# Release: $Name:  $
# Version: $Revision: 1.2 $
# Date: $Date: 1999/04/06 20:57:23 $
#
############################################################

# First, build the classes and the custom.jar

cd custom_src
./build
./buildCustomJar

# Second, build the loader files
cd ../loader/source
./build
