#!/bin/sh
#
# Ganymede server jar build script
#
# Version: $Revision: 1.5 $
# Date: $Date: 1999/01/20 18:58:26 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

# And do the build

echo "Building admin jar"

mv -f ganymedeServer.jar ganymedeServer.jar.old

cd server_classes

# We need the Util package for lots of things

ln -s ../arlut/csd/Util arlut/csd/Util

# We need a few things from JDataComponent

rm -rf arlut/csd/JDataComponent
mkdir arlut/csd/JDataComponent
ln -s ../arlut/csd/JDataComponent/listHandle.class arlut/csd/JDataComponent
ln -s ../arlut/csd/JDialog arlut/csd/JDialog
ln -s ../jcrypt.class .
ln -s ../Qsmtp.class .

./sync_tree
./sync_tree.gnu

$JAVADIR/jar -cf ../ganymedeServer.jar arlut gnu jcrypt.class Qsmtp.class

cd ..

echo "Done building server jar"

