#!/bin/sh
#
# Ganymede admin jar build script
#
# Version: $Revision: 1.7 $
# Date: $Date: 1999/01/20 19:24:50 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

# And do the build

echo "Building admin jar"

mv -f ganymedeAdmin.jar ganymedeAdmin.jar.old

cd admin_classes

# We need the Util directory as well

cd arlut/csd
rm -f Util
ln -s $CLASSDIR/arlut/csd/Util .
cd ../..

./sync_tree

$JAVADIR/jar -cf ../ganymedeAdmin.jar arlut

cd ..

echo "Done building admin jar"

