#!/bin/sh
#
# Ganymede server jar build script
#
# Version: $Revision: 1.14 $
# Date: $Date: 1999/08/05 22:06:46 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. ./config.sh

# And do the build

echo "Building server jar"

cd $TARGETDIR

mv -f ganymedeServer.jar ganymedeServer.jar.old > /dev/null 2>&1

cd server_classes

# We need the Util package for lots of things

cd arlut/csd
rm -f Util
ln -s $TARGETDIR/arlut/csd/Util .
cd ../..

# We need one thing from JDataComponent

rm -rf arlut/csd/JDataComponent
mkdir arlut/csd/JDataComponent

cd arlut/csd/JDataComponent
rm -f listHandle.class
ln -s $TARGETDIR/arlut/csd/JDataComponent/listHandle.class .
cd ../../..

# And we need the JDialog package for the serializable
# dialog objects

cd arlut/csd
rm -f JDialog
ln -s $TARGETDIR/arlut/csd/JDialog .
cd ../..

rm -f jcrypt.class
ln -s ../jcrypt.class .

rm -f Qsmtp.class
ln -s ../Qsmtp.class .

rm -f messageObject.class
ln -s ../messageObject.class .

rm -f MD5.class
ln -s ../MD5.class .

rm -f MD5InputStream.class
ln -s ../MD5InputStream.class .

rm -f MD5OutputStream.class
ln -s ../MD5OutputStream.class .

rm -f MD5State.class
ln -s ../MD5State.class .

./sync_tree
./sync_tree.gnu

$JAVADIR/jar -cf ../ganymedeServer.jar arlut gnu jcrypt.class Qsmtp.class messageObject.class MD5*.class

cd ..

echo "Done building server jar"

