#!/bin/csh

cd /home/broccol/gash2/classes

mv ganymedeServer.jar ganymedeServer.jar.old

cd server_classes

./sync_tree
./sync_tree.gnu

/opt/bin/jar -cf ../ganymedeServer.jar arlut gnu jcrypt.class Qsmtp.class

cd ..

# Now install the jar file where we will use it

#cp ganymedeAdmin.jar /home/broccol/public_html/gash2
#chmod 664 /home/broccol/public_html/gash2/ganymedeAdmin.jar
#cp ganymedeAdmin.jar /opt/depot/ganymede/etc
#chmod 664 /opt/depot/ganymede/etc/ganymedeAdmin.jar

