#!/bin/sh
#
# Ganymede client jar build script
#
# Version: $Revision: 1.5 $
# Date: $Date: 1999/01/20 17:45:49 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

# And do the build

echo "Building client jar"

mv -f ganymede.jar ganymede.jar.old

cd client_classes

sync_tree

$JAVADIR/jar -cf ../ganymede.jar arlut

cd ..

echo "Done building client jar"