#!/bin/sh
#
# Ganymede admin jar build script
#
# Version: $Revision: 1.13 $
# Date: $Date: 1999/06/19 03:20:56 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. ./config.sh

# And do the build

cd $TARGETDIR

echo "Building admin jar"

mv -f ganymedeAdmin.jar ganymedeAdmin.jar.old > /dev/null 2>&1

cd admin_classes

# We need the Util directory as well

cd arlut/csd
rm -f Util
ln -s $TARGETDIR/arlut/csd/Util .
cd ../..

# And the JDataComponent directory

cd arlut/csd
rm -f JDataComponent
ln -s $TARGETDIR/arlut/csd/JDataComponent JDataComponent
cd ../..

# And the JDialog directory

cd arlut/csd
rm -f JDialog
ln -s $TARGETDIR/arlut/csd/JDialog JDialog
cd ../..

# And the JTable directory

cd arlut/csd
rm -f JTable
ln -s $TARGETDIR/arlut/csd/JTable JTable
cd ../..

# And the JTree directory

cd arlut/csd
rm -f JTree
ln -s $TARGETDIR/arlut/csd/JTree JTree
cd ../..

# And get the subset of the arlut.csd.ganymede classes we need symlinked
# into our admin_classes directory for inclusion in the jar

./sync_tree

$JAVADIR/jar -cf ../ganymedeAdmin.jar arlut

cd ..

echo "Done building admin jar"

