#!/bin/sh
#
# Ganymede build script
#
# Release: $Name:  $
# Version: $Revision: 1.3 $
# Date: $Date: 1999/01/21 23:41:46 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

##################################################

CLASSPATH=$CLASSDIR:../../custom_src/classes:$CLASSPATH; export CLASSPATH
export CLASSPATH

echo "Compiling $COMPNAME Loader files"

$JAVAC -deprecation -d $TARGETDIR *.java

echo "Building rmi stubs and skeletons"

$RMIC -d $TARGETDIR arlut.csd.ganymede.loader.directLoaderClient

echo "Done"

