#!/bin/sh
#
# Ganymede Password Clients Build Script
#
# Release: $Name:  $
# Version: $Revision: 1.4 $
# Date: $Date: 1999/01/22 00:04:55 $
#
###################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

echo "Compiling $COMPNAME"

CLASSPATH=$CLASSDIR:$CLASSPATH; export CLASSPATH

$JAVAC -deprecation -d $TARGETDIR *.java

echo "Creating Jar file"

cd $TARGETDIR

$JAVADIR/jar -cf $currentdir/../../jars/password.jar arlut

cd $currentdir

echo "Done"
