#!/bin/sh
#
# Ganymede phone client script
#
####################################

# The following are customized by the installClient.perl script
# and should not have anything other than X=Y on each line

JAVA=/opt/bin/java
PROPERTIES=/ganymede/site/ganymede-client/client.properties
JARDIR=/ganymede/site/ganymede-client/jars

# Script

CLASSPATH=${JARDIR}/ganymede.jar
export CLASSPATH

$JAVA arlut.csd.ganymede.client.arl_phone.phoneClient $PROPERTIES
