#!/bin/sh
#
# Ganymede client script
#
########################

## This section is customized by the client install script

# These lines should be in the form X=Y, with nothing else on
# the line.. they are customized by the installClient.perl
# script

JAVA=java
CLASSPATH=../../build/classes:../../build/crypto:../../resources
PROPERTIES=/home/deepak/devel/ganymede/client/client.properties

############################################### 

trap "echo Aborted" 2

echo "Running Ganymede Client"

export CLASSPATH

# For Java 1.2/1.3

$JAVA -Xmx48m arlut.csd.ganymede.client.glogin properties=$PROPERTIES
