#!/bin/sh
#
# Ganymede XML client script
#
# Usage: xmlclient username=<username> [password=<password>] <xmlfilename>
#
# Last Revision Changed: $Rev: 5859 $
# Last Changed By: $Author: broccol $
# Last Mod Date: $Date: 2004-12-01 02:12:29 -0600 (Wed, 01 Dec 2004) $
#
# Module by: Jonathan Abbey, jonabbey@arlut.utexas.edu, ARL:UT
#
##############################################################

## This section is customized by the client install script

# These lines should be in the form X=Y, with nothing else on
# the line.. they are customized by the installClient.perl
# script

JAVA=java
INSTALLDIR=/home/deepak/devel/ganymede/client
CLASSPATH=../../build/classes:../../build/crypto/

PROPERTIES=${INSTALLDIR}/client.properties

############################################### 

trap "echo Aborted" 2

export CLASSPATH

stty -echo
$JAVA arlut.csd.ganymede.client.xmlclient properties=$PROPERTIES $*;SAVE=$?
stty echo

exit $SAVE

