#!/bin/sh
#
# Ganymede client build script
#
# Release: $Name:  $
# Version: $Revision: 1.8 $
# Date: $Date: 2000/09/17 08:14:51 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. ./config.sh

# And do the build

echo "Compiling $COMPNAME"

umask 022;

CLASSPATH=$CLASSDIR:$CLASSPATH; export CLASSPATH
$JAVAC -J-mx128m -deprecation -d $TARGETDIR *.java

echo "Building rmi stubs and skeletons"

$JAVADIR/rmic -d $TARGETDIR arlut.csd.ganymede.client.ClientBase
$JAVADIR/rmic -d $TARGETDIR arlut.csd.ganymede.client.FileReceiverBase

# Return to our last directory

cd $currentdir

echo "Done compiling $COMPNAME"
