#!/bin/sh
#
# Ganymede client build script
#
# Release: $Name:  $
# Version: $Revision: 1.5 $
# Date: $Date: 1999/01/26 19:14:20 $
#
############################################################

currentdir=`pwd`

# Change to the directory where this build script is

prog=$0
builddir=`echo $prog|sed 's%/[^/][^/]*$%%'`
test "x$builddir" = "x$builddir" && builddir=.
cd $builddir

# Load configuration information

. config.sh

# And do the build

echo "Compiling $COMPNAME"

umask 022;

CLASSPATH=$CLASSDIR:$CLASSPATH; export CLASSPATH
$JAVAC -J-mx128m -deprecation -d $CLASSDIR *.java

echo "Building rmi stubs and skeletons"

$JAVADIR/rmic -d $CLASSDIR arlut.csd.ganymede.client.ClientBase

# Return to our last directory

cd $currentdir

echo "Done compiling $COMPNAME"
