#!/bin/sh
#
# Ganymede build script for James Clark's XP XML Parser Code
#
# Release: $Name:  $
# Version: $Revision: 1.2 $
# Date: $Date: 2000/02/21 19:51:50 $
#
############################################################

# Build James Clark's custom hashtable class

cd util
./build

# Build James Clark's XML Parser

# first the Version.java file

cd ../xml
./build

# then the Tokenizer

cd tok
./build

# then the Parser

cd ../parse
./build

# then the SAX driver

cd ../sax
./build

# and finally the XMLWriter classes

cd ../output
./build
