#!/bin/sh
#
# Ganymede schema kit build script
#
# Release: $Name:  $
# Version: $Revision: 1.1 $
# Date: $Date: 1999/08/18 21:09:59 $
#
############################################################

# First, build the classes and the custom.jar

cd custom_src
./build
./buildCustomJar

# Second, build the loader files
cd ../loader/source
./build
